---
- name: Download and Unarchive Spark 2.2.0
  unarchive:
    src: https://archive.apache.org/dist/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz
    dest: /usr/lib/spark_2.2.0 
    remote_src: yes
- name: Download and Unarchive Analytics Zoo 
  unarchive:
    src: https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/zoo/analytics-zoo-bigdl_0.6.0-spark_2.2.0/0.3.0-SNAPSHOT/analytics-zoo-bigdl_0.6.0-spark_2.2.0-0.3.0-20181011.180658-95-dist-all.zip
    dest: /usr/lib/analytics_zoo
    remote_src: yes
